// Code generated by "stringer -type=DistType,LEFMode -linecomment"; DO NOT EDIT.

package fair

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DistDefault-0]
	_ = x[DistPERT-1]
	_ = x[DistPoisson-2]
	_ = x[DistLogNormal-3]
	_ = x[DistBeta-4]
}

const _DistType_name = "defaultpertpoissonlognormalbeta"

var _DistType_index = [...]uint8{0, 7, 11, 18, 27, 31}

func (i DistType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DistType_index)-1 {
		return "DistType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DistType_name[_DistType_index[idx]:_DistType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LEFDecomposed-0]
	_ = x[LEFDirect-1]
}

const _LEFMode_name = "decomposeddirect"

var _LEFMode_index = [...]uint8{0, 10, 16}

func (i LEFMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LEFMode_index)-1 {
		return "LEFMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LEFMode_name[_LEFMode_index[idx]:_LEFMode_index[idx+1]]
}
